[[pages]]
path = "pages_view/board.py"
name = "Trang chủ"
icon = ":material/home:"

[[pages]]
name = "Reports"
icon = ""
is_section = true

[[pages]]
path = "pages_view/home.py"
name = "Giới thiệu"
icon = ":material/contacts:"

[[pages]]
path = "pages_view/view.py"
name = "Dự đoán"
icon = ":material/dashboard:"

[[pages]]
name = "Account"
icon = ""
is_section = true

[[pages]]
path = "pages_view/expand.py"
name = "Mở rộng"
icon = ":material/top_panel_open:"

[[pages]]
path = "pages_view/users.py"
name = "Người dùng"
icon = ":material/manage_accounts:"



